### ISSUE TITLE
How to set the height of the Tree？ 

### ISSUE THREAD

**Issue by 700001280** [TatuLund/tree-flow#1]
Thank you for your contributions. I used the Tree in MainView and add to Drawer. I want to set the height to full. Would you please show how to set? Thanks.
![WeChat Image_20200220182031](https://user-images.githubusercontent.com/6184189/74924658-c97de300-540d-11ea-9a83-812503a3cd8e.png)

**Comment by TatuLund** [comment]
Yes, I forgot to implement HasSize, and some details. Should be ok now in version 1.1.0.
