### ISSUE TITLE
Provide a `scrollToIndex(int...)` method

### ISSUE THREAD

**Issue by javier-godoy** [TatuLund/tree-flow#8]
Provide a `scrollToIndex(int...)` method that delegates into the new [`TreeGrid.scrollToIndex(int...)` method](https://github.com/vaadin/flow-components/blob/fea4ce11d8874280a365f7544b0efc8067999464/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java#L1064-L1078) that was added in Vaadin 24.1

**Comment by TatuLund** [comment]
Added in version 3.3.0
